export const actionTypes = {
  START_GAME: "START_GAME",
  MOVE_RIGHT: "MOVE_RIGHT",
  MOVE_LEFT: "MOVE_LEFT",
  MOVE_UP: "MOVE_UP",
  MOVE_DOWN: "MOVE_DOWN",
  CHECK_GAME_OVER: "CHECK_GAME_OVER",
};
